export const VOICE_FILTERS = [
  {
    id: "normal",
    name: "You",
    detail: "Your own voice",
    pitch: 1,
    ringHz: 0,
    ringMix: 0,
    lowpassHz: 18000,
    highpassHz: 0,
    drive: 1,
    echoMix: 0,
  },
  {
    id: "cat",
    name: "Cat",
    detail: "Tiny, squeaky chaos",
    pitch: 1.65,
    ringHz: 0,
    ringMix: 0,
    lowpassHz: 6000,
    highpassHz: 260,
    drive: 1.3,
    echoMix: 0,
  },
  {
    id: "robot",
    name: "Robot",
    detail: "Metal mouth",
    pitch: 0.92,
    ringHz: 55,
    ringMix: 0.75,
    lowpassHz: 4500,
    highpassHz: 160,
    drive: 2,
    echoMix: 0,
  },
  {
    id: "kid",
    name: "Kid",
    detail: "Small voice, big trouble",
    pitch: 1.35,
    ringHz: 0,
    ringMix: 0,
    lowpassHz: 9000,
    highpassHz: 140,
    drive: 1,
    echoMix: 0,
  },
  {
    id: "fairy",
    name: "Fairy",
    detail: "Bright and floaty",
    pitch: 1.23,
    ringHz: 0,
    ringMix: 0,
    lowpassHz: 11000,
    highpassHz: 160,
    drive: 1,
    echoMix: 0.16,
  },
  {
    id: "giant",
    name: "Giant",
    detail: "Deep table-shaker",
    pitch: 0.7,
    ringHz: 0,
    ringMix: 0,
    lowpassHz: 3800,
    highpassHz: 50,
    drive: 1.5,
    echoMix: 0,
  },
  {
    id: "monster",
    name: "Monster",
    detail: "Low growl energy",
    pitch: 0.6,
    ringHz: 32,
    ringMix: 0.28,
    lowpassHz: 3200,
    highpassHz: 60,
    drive: 3,
    echoMix: 0,
  },
  {
    id: "alien",
    name: "Alien",
    detail: "From another planet",
    pitch: 1.12,
    ringHz: 110,
    ringMix: 0.6,
    lowpassHz: 7000,
    highpassHz: 200,
    drive: 1.2,
    echoMix: 0.12,
  },
  {
    id: "chipmunk",
    name: "Chipmunk",
    detail: "Maximum squeak",
    pitch: 1.9,
    ringHz: 0,
    ringMix: 0,
    lowpassHz: 8000,
    highpassHz: 350,
    drive: 1,
    echoMix: 0,
  },
  {
    id: "radio",
    name: "Radio",
    detail: "Over and out",
    pitch: 1,
    ringHz: 0,
    ringMix: 0,
    lowpassHz: 2800,
    highpassHz: 600,
    drive: 3,
    echoMix: 0,
  },
] as const

export type VoiceFilterId = (typeof VOICE_FILTERS)[number]["id"]
export type VoiceFilterPreset = (typeof VOICE_FILTERS)[number]

export function getVoiceFilter(value: unknown): VoiceFilterPreset {
  return VOICE_FILTERS.find((filter) => filter.id === value) ?? VOICE_FILTERS[0]
}
